# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "processor_metadata_schema.rs"
schema = "processor_metadata"

[migrations_directory]
dir = "migrations"
